public enum SoundClips {
	_None = 0,
	MoldSpawn = 1,
	PlayerFloating = 2,
	HappyAbilityHit = 3,
	HealAbility = 4,
	EnemyAmbience = 5,
	EnemyScreech = 6,
	EnemyCry = 7,
	EnemyFly = 8,
	MoldExplode = 9,
	MoldHit = 10,
	MoldSound = 11,
	Crystal = 12,
	CrystalBreak = 13,
	PlayerHair = 14,
	PlayerMoan = 15,
	BattleSong = 16,
	RestSong = 17,
	MenuSong = 18,
	ForestAmbience = 19,
	HappyRay = 20,
	HappyAreaDamage = 21,
	HappyAttack = 22,
}
